/**
 * Booking notification — emails the marketing/counselling team + IPD
 * coordinators on every (non-test) booking, with the scheduling flag and the
 * SREWS risk tier. Reuses the same Resend sender as send-reminder/route.ts.
 *
 * Recipients come from the BOOKING_NOTIFY_EMAILS env var (comma-separated).
 * If the key or recipients are missing, we skip silently (never break a
 * booking over a notification).
 */
import type { BookingFormData } from './booking-types';

function getResend() {
  const { Resend } = require('resend');
  return new Resend(process.env.RESEND_API_KEY);
}

function recipients(): string[] {
  return (process.env.BOOKING_NOTIFY_EMAILS || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

const TIER_COLOUR: Record<string, string> = {
  GREEN: '#16a34a',
  AMBER: '#d97706',
  RED: '#dc2626',
  CRITICAL: '#7f1d1d',
};

export async function notifyBooking(d: BookingFormData, flag: string, tier?: string): Promise<void> {
  if (d.is_test) return; // never email for test submissions
  if (!process.env.RESEND_API_KEY) {
    console.warn('[booking notify] RESEND_API_KEY not set; skipping email');
    return;
  }
  const to = recipients();
  if (to.length === 0) {
    console.warn('[booking notify] BOOKING_NOTIFY_EMAILS not set; skipping email');
    return;
  }

  const esc = (v?: string) =>
    (v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const row = (k: string, v?: string) =>
    v ? `<tr><td style="padding:5px 10px;font-weight:bold;color:#555">${k}</td><td style="padding:5px 10px">${esc(v)}</td></tr>` : '';
  const tierBadge = tier
    ? `<span style="background:${TIER_COLOUR[tier] || '#555'};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px">${esc(tier)}</span>`
    : '— (pending)';

  try {
    const resend = getResend();
    await resend.emails.send({
      from: 'EHRC Dashboard <notifications@notifications.even.in>',
      to,
      subject: `New Surgery Booking: ${esc(d.patient_name)} — ${esc(d.surgeon_name)} — ${esc(d.surgery_date)}`,
      html: `<div style="font-family:Arial,sans-serif;max-width:620px">
        <h3 style="color:#1f4e78;margin-bottom:4px">New Surgery Booking</h3>
        <table style="border-collapse:collapse;width:100%">
          ${row('Patient', d.patient_name)}
          ${row('UHID', d.uhid)}
          ${row('Surgeon', d.surgeon_name)}
          ${row('Procedure', d.proposed_procedure)}
          ${row('Surgery date', d.surgery_date)}
          ${row('Surgery time', d.surgery_time)}
          ${row('Admission', `${d.admission_date || ''} ${d.admission_time || ''}`.trim())}
          ${row('Urgency', d.urgency)}
          ${row('Payer', d.payer)}
          ${row('Counselled by', d.counselled_by)}
          <tr><td style="padding:5px 10px;font-weight:bold;color:#555">Scheduling flag</td><td style="padding:5px 10px">${esc(flag) || 'Requested time and dates OK'}</td></tr>
          <tr><td style="padding:5px 10px;font-weight:bold;color:#555">SREWS risk tier</td><td style="padding:5px 10px">${tierBadge}</td></tr>
        </table>
        <p style="margin-top:12px;font-size:13px"><a href="https://ehrc-daily-dash.vercel.app/admin/surgical-risk">Open risk dashboard</a></p>
        <p style="font-size:11px;color:#999">Auto-generated by EHRC Surgery Booking</p>
      </div>`,
    });
  } catch (e) {
    console.warn('[booking notify] send failed:', e);
  }
}
